version: "3.8"

services:
  php-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      - XDEBUG_MODE=coverage
